/* tslint:disable */
/* eslint-disable */
/**
 * machina
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CursorPaginatedStringVecListenDataInner } from './CursorPaginatedStringVecListenDataInner';
import {
    CursorPaginatedStringVecListenDataInnerFromJSON,
    CursorPaginatedStringVecListenDataInnerFromJSONTyped,
    CursorPaginatedStringVecListenDataInnerToJSON,
    CursorPaginatedStringVecListenDataInnerToJSONTyped,
} from './CursorPaginatedStringVecListenDataInner';

/**
 * 
 * @export
 * @interface CursorPaginatedStringVecListen
 */
export interface CursorPaginatedStringVecListen {
    /**
     * 
     * @type {string}
     * @memberof CursorPaginatedStringVecListen
     */
    cursor?: string;
    /**
     * 
     * @type {Array<CursorPaginatedStringVecListenDataInner>}
     * @memberof CursorPaginatedStringVecListen
     */
    data: Array<CursorPaginatedStringVecListenDataInner>;
}

/**
 * Check if a given object implements the CursorPaginatedStringVecListen interface.
 */
export function instanceOfCursorPaginatedStringVecListen(value: object): value is CursorPaginatedStringVecListen {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CursorPaginatedStringVecListenFromJSON(json: any): CursorPaginatedStringVecListen {
    return CursorPaginatedStringVecListenFromJSONTyped(json, false);
}

export function CursorPaginatedStringVecListenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPaginatedStringVecListen {
    if (json == null) {
        return json;
    }
    return {
        
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'data': ((json['data'] as Array<any>).map(CursorPaginatedStringVecListenDataInnerFromJSON)),
    };
}

export function CursorPaginatedStringVecListenToJSON(json: any): CursorPaginatedStringVecListen {
    return CursorPaginatedStringVecListenToJSONTyped(json, false);
}

export function CursorPaginatedStringVecListenToJSONTyped(value?: CursorPaginatedStringVecListen | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cursor': value['cursor'],
        'data': ((value['data'] as Array<any>).map(CursorPaginatedStringVecListenDataInnerToJSON)),
    };
}

