/* tslint:disable */
/* eslint-disable */
/**
 * machina
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopTrack
 */
export interface TopTrack {
    /**
     * 
     * @type {string}
     * @memberof TopTrack
     */
    albumArt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TopTrack
     */
    albumName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TopTrack
     */
    artistName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TopTrack
     */
    duration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TopTrack
     */
    listenCount: number;
    /**
     * 
     * @type {string}
     * @memberof TopTrack
     */
    trackId: string;
    /**
     * 
     * @type {string}
     * @memberof TopTrack
     */
    trackName: string;
}

/**
 * Check if a given object implements the TopTrack interface.
 */
export function instanceOfTopTrack(value: object): value is TopTrack {
    if (!('listenCount' in value) || value['listenCount'] === undefined) return false;
    if (!('trackId' in value) || value['trackId'] === undefined) return false;
    if (!('trackName' in value) || value['trackName'] === undefined) return false;
    return true;
}

export function TopTrackFromJSON(json: any): TopTrack {
    return TopTrackFromJSONTyped(json, false);
}

export function TopTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopTrack {
    if (json == null) {
        return json;
    }
    return {
        
        'albumArt': json['album_art'] == null ? undefined : json['album_art'],
        'albumName': json['album_name'] == null ? undefined : json['album_name'],
        'artistName': json['artist_name'] == null ? undefined : json['artist_name'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'listenCount': json['listen_count'],
        'trackId': json['track_id'],
        'trackName': json['track_name'],
    };
}

export function TopTrackToJSON(json: any): TopTrack {
    return TopTrackToJSONTyped(json, false);
}

export function TopTrackToJSONTyped(value?: TopTrack | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'album_art': value['albumArt'],
        'album_name': value['albumName'],
        'artist_name': value['artistName'],
        'duration': value['duration'],
        'listen_count': value['listenCount'],
        'track_id': value['trackId'],
        'track_name': value['trackName'],
    };
}

