/* tslint:disable */
/* eslint-disable */
/**
 * machina
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotalListenStats
 */
export interface TotalListenStats {
    /**
     * 
     * @type {number}
     * @memberof TotalListenStats
     */
    totalSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof TotalListenStats
     */
    uniqueTracksCount: number;
}

/**
 * Check if a given object implements the TotalListenStats interface.
 */
export function instanceOfTotalListenStats(value: object): value is TotalListenStats {
    if (!('totalSeconds' in value) || value['totalSeconds'] === undefined) return false;
    if (!('uniqueTracksCount' in value) || value['uniqueTracksCount'] === undefined) return false;
    return true;
}

export function TotalListenStatsFromJSON(json: any): TotalListenStats {
    return TotalListenStatsFromJSONTyped(json, false);
}

export function TotalListenStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalListenStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSeconds': json['total_seconds'],
        'uniqueTracksCount': json['unique_tracks_count'],
    };
}

export function TotalListenStatsToJSON(json: any): TotalListenStats {
    return TotalListenStatsToJSONTyped(json, false);
}

export function TotalListenStatsToJSONTyped(value?: TotalListenStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_seconds': value['totalSeconds'],
        'unique_tracks_count': value['uniqueTracksCount'],
    };
}

