/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as DevImport } from './routes/dev'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PUserIdImport } from './routes/p/$userId'
import { Route as DirectSplatImport } from './routes/direct/$'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const DevRoute = DevImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const PUserIdRoute = PUserIdImport.update({
  id: '/p/$userId',
  path: '/p/$userId',
  getParentRoute: () => rootRoute,
} as any)

const DirectSplatRoute = DirectSplatImport.update({
  id: '/direct/$',
  path: '/direct/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/direct/$': {
      id: '/direct/$'
      path: '/direct/$'
      fullPath: '/direct/$'
      preLoaderRoute: typeof DirectSplatImport
      parentRoute: typeof rootRoute
    }
    '/p/$userId': {
      id: '/p/$userId'
      path: '/p/$userId'
      fullPath: '/p/$userId'
      preLoaderRoute: typeof PUserIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dev': typeof DevRoute
  '/signin': typeof SigninRoute
  '/direct/$': typeof DirectSplatRoute
  '/p/$userId': typeof PUserIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dev': typeof DevRoute
  '/signin': typeof SigninRoute
  '/direct/$': typeof DirectSplatRoute
  '/p/$userId': typeof PUserIdRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dev': typeof DevRoute
  '/signin': typeof SigninRoute
  '/direct/$': typeof DirectSplatRoute
  '/p/$userId': typeof PUserIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/dev'
    | '/signin'
    | '/direct/$'
    | '/p/$userId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dev'
    | '/signin'
    | '/direct/$'
    | '/p/$userId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/dev'
    | '/signin'
    | '/direct/$'
    | '/p/$userId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevRoute: typeof DevRoute
  SigninRoute: typeof SigninRoute
  DirectSplatRoute: typeof DirectSplatRoute
  PUserIdRoute: typeof PUserIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevRoute: DevRoute,
  SigninRoute: SigninRoute,
  DirectSplatRoute: DirectSplatRoute,
  PUserIdRoute: PUserIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/dashboard",
        "/dev",
        "/signin",
        "/direct/$",
        "/p/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/"
      ]
    },
    "/dev": {
      "filePath": "dev.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/direct/$": {
      "filePath": "direct/$.tsx"
    },
    "/p/$userId": {
      "filePath": "p/$userId.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
