/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeEmailPost200Response {
    /// Indicates if the request was successful
    #[serde(rename = "status")]
    pub status: bool,
    /// Status message of the email change process
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<Message>,
}

impl ChangeEmailPost200Response {
    pub fn new(status: bool) -> ChangeEmailPost200Response {
        ChangeEmailPost200Response {
            status,
            message: None,
        }
    }
}
/// Status message of the email change process
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "Email updated")]
    EmailUpdated,
    #[serde(rename = "Verification email sent")]
    VerificationEmailSent,
}

impl Default for Message {
    fn default() -> Message {
        Self::EmailUpdated
    }
}

