/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeEmailPostRequest {
    /// The new email to set
    #[serde(rename = "newEmail")]
    pub new_email: String,
    /// The URL to redirect to after email verification
    #[serde(rename = "callbackURL", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<String>,
}

impl ChangeEmailPostRequest {
    pub fn new(new_email: String) -> ChangeEmailPostRequest {
        ChangeEmailPostRequest {
            new_email,
            callback_url: None,
        }
    }
}

