/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePasswordPostRequest {
    /// The new password to set
    #[serde(rename = "newPassword")]
    pub new_password: String,
    /// The current password
    #[serde(rename = "currentPassword")]
    pub current_password: String,
    /// Revoke all other sessions
    #[serde(rename = "revokeOtherSessions", skip_serializing_if = "Option::is_none")]
    pub revoke_other_sessions: Option<String>,
}

impl ChangePasswordPostRequest {
    pub fn new(new_password: String, current_password: String) -> ChangePasswordPostRequest {
        ChangePasswordPostRequest {
            new_password,
            current_password,
            revoke_other_sessions: None,
        }
    }
}

