/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteUserCallbackGet200Response {
    /// Indicates if the deletion was successful
    #[serde(rename = "success")]
    pub success: bool,
    /// Confirmation message
    #[serde(rename = "message")]
    pub message: Message,
}

impl DeleteUserCallbackGet200Response {
    pub fn new(success: bool, message: Message) -> DeleteUserCallbackGet200Response {
        DeleteUserCallbackGet200Response {
            success,
            message,
        }
    }
}
/// Confirmation message
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "User deleted")]
    UserDeleted,
}

impl Default for Message {
    fn default() -> Message {
        Self::UserDeleted
    }
}

