/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteUserPost200Response {
    /// Indicates if the operation was successful
    #[serde(rename = "success")]
    pub success: bool,
    /// Status message of the deletion process
    #[serde(rename = "message")]
    pub message: Message,
}

impl DeleteUserPost200Response {
    pub fn new(success: bool, message: Message) -> DeleteUserPost200Response {
        DeleteUserPost200Response {
            success,
            message,
        }
    }
}
/// Status message of the deletion process
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "User deleted")]
    UserDeleted,
    #[serde(rename = "Verification email sent")]
    VerificationEmailSent,
}

impl Default for Message {
    fn default() -> Message {
        Self::UserDeleted
    }
}

