/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSessionGet200Response {
    #[serde(rename = "session")]
    pub session: Box<models::Session>,
    #[serde(rename = "user")]
    pub user: Box<models::User>,
}

impl GetSessionGet200Response {
    pub fn new(session: models::Session, user: models::User) -> GetSessionGet200Response {
        GetSessionGet200Response {
            session: Box::new(session),
            user: Box::new(user),
        }
    }
}

