/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkSocialPost200Response {
    /// The authorization URL to redirect the user to
    #[serde(rename = "url")]
    pub url: String,
    /// Indicates if the user should be redirected to the authorization URL
    #[serde(rename = "redirect")]
    pub redirect: bool,
}

impl LinkSocialPost200Response {
    pub fn new(url: String, redirect: bool) -> LinkSocialPost200Response {
        LinkSocialPost200Response {
            url,
            redirect,
        }
    }
}

