/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkSocialPostRequest {
    /// The URL to redirect to after the user has signed in
    #[serde(rename = "callbackURL", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<String>,
    /// The OAuth2 provider to use
    #[serde(rename = "provider")]
    pub provider: String,
    /// Additional scopes to request from the provider
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<String>,
}

impl LinkSocialPostRequest {
    pub fn new(provider: String) -> LinkSocialPostRequest {
        LinkSocialPostRequest {
            callback_url: None,
            provider,
            scopes: None,
        }
    }
}

