/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Oauth2CallbackProviderIdGet200Response {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl Oauth2CallbackProviderIdGet200Response {
    pub fn new() -> Oauth2CallbackProviderIdGet200Response {
        Oauth2CallbackProviderIdGet200Response {
            url: None,
        }
    }
}

