/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Oauth2LinkPostRequest {
    #[serde(rename = "providerId")]
    pub provider_id: String,
    #[serde(rename = "callbackURL")]
    pub callback_url: String,
}

impl Oauth2LinkPostRequest {
    pub fn new(provider_id: String, callback_url: String) -> Oauth2LinkPostRequest {
        Oauth2LinkPostRequest {
            provider_id,
            callback_url,
        }
    }
}

