/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Oauth2LinkPost200Response {
    /// The authorization URL to redirect the user to for linking the OAuth2 account
    #[serde(rename = "url")]
    pub url: String,
    /// Indicates that the client should redirect to the provided URL
    #[serde(rename = "redirect")]
    pub redirect: Redirect,
}

impl Oauth2LinkPost200Response {
    pub fn new(url: String, redirect: Redirect) -> Oauth2LinkPost200Response {
        Oauth2LinkPost200Response {
            url,
            redirect,
        }
    }
}
/// Indicates that the client should redirect to the provided URL
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Redirect {
    #[serde(rename = "true")]
    True,
}

impl Default for Redirect {
    fn default() -> Redirect {
        Self::True
    }
}

