/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OkGet200Response {
    /// Indicates if the API is working
    #[serde(rename = "ok")]
    pub ok: bool,
}

impl OkGet200Response {
    pub fn new(ok: bool) -> OkGet200Response {
        OkGet200Response {
            ok,
        }
    }
}

