/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshTokenPostRequest {
    /// The provider ID for the OAuth provider
    #[serde(rename = "providerId")]
    pub provider_id: String,
    /// The account ID associated with the refresh token
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The user ID associated with the account
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl RefreshTokenPostRequest {
    pub fn new(provider_id: String) -> RefreshTokenPostRequest {
        RefreshTokenPostRequest {
            provider_id,
            account_id: None,
            user_id: None,
        }
    }
}

