/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetPasswordPostRequest {
    /// The new password to set
    #[serde(rename = "newPassword")]
    pub new_password: String,
    /// The token to reset the password
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl ResetPasswordPostRequest {
    pub fn new(new_password: String) -> ResetPasswordPostRequest {
        ResetPasswordPostRequest {
            new_password,
            token: None,
        }
    }
}

