/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeSessionsPost200Response {
    /// Indicates if all sessions were revoked successfully
    #[serde(rename = "status")]
    pub status: bool,
}

impl RevokeSessionsPost200Response {
    pub fn new(status: bool) -> RevokeSessionsPost200Response {
        RevokeSessionsPost200Response {
            status,
        }
    }
}

