/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeSessionPostRequest {
    /// The token to revoke
    #[serde(rename = "token")]
    pub token: String,
}

impl RevokeSessionPostRequest {
    pub fn new(token: String) -> RevokeSessionPostRequest {
        RevokeSessionPostRequest {
            token,
        }
    }
}

