/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendVerificationEmailPostRequest {
    /// The email to send the verification email to
    #[serde(rename = "email")]
    pub email: String,
    /// The URL to use for email verification callback
    #[serde(rename = "callbackURL", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<String>,
}

impl SendVerificationEmailPostRequest {
    pub fn new(email: String) -> SendVerificationEmailPostRequest {
        SendVerificationEmailPostRequest {
            email,
            callback_url: None,
        }
    }
}

