/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendVerificationEmailPost200Response {
    /// Indicates if the email was sent successfully
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<bool>,
}

impl SendVerificationEmailPost200Response {
    pub fn new() -> SendVerificationEmailPost200Response {
        SendVerificationEmailPost200Response {
            status: None,
        }
    }
}

