/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignUpEmailPost200ResponseUser {
    /// The unique identifier of the user
    #[serde(rename = "id")]
    pub id: String,
    /// The email address of the user
    #[serde(rename = "email")]
    pub email: String,
    /// The name of the user
    #[serde(rename = "name")]
    pub name: String,
    /// The profile image URL of the user
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Whether the email has been verified
    #[serde(rename = "emailVerified")]
    pub email_verified: bool,
    /// When the user was created
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// When the user was last updated
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl SignUpEmailPost200ResponseUser {
    pub fn new(id: String, email: String, name: String, email_verified: bool, created_at: String, updated_at: String) -> SignUpEmailPost200ResponseUser {
        SignUpEmailPost200ResponseUser {
            id,
            email,
            name,
            image: None,
            email_verified,
            created_at,
            updated_at,
        }
    }
}

