/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignInEmailPost200Response : Session response when idToken is provided
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignInEmailPost200Response {
    #[serde(rename = "redirect")]
    pub redirect: Redirect,
    /// Session token
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<serde_json::Value>>,
    #[serde(rename = "user")]
    pub user: Box<models::SignInEmailPost200ResponseUser>,
}

impl SignInEmailPost200Response {
    /// Session response when idToken is provided
    pub fn new(redirect: Redirect, token: String, user: models::SignInEmailPost200ResponseUser) -> SignInEmailPost200Response {
        SignInEmailPost200Response {
            redirect,
            token,
            url: None,
            user: Box::new(user),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Redirect {
    #[serde(rename = "false")]
    False,
}

impl Default for Redirect {
    fn default() -> Redirect {
        Self::False
    }
}

