/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignInEmailPostRequest {
    /// Email of the user
    #[serde(rename = "email")]
    pub email: String,
    /// Password of the user
    #[serde(rename = "password")]
    pub password: String,
    /// Callback URL to use as a redirect for email verification
    #[serde(rename = "callbackURL", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<String>,
    /// If this is false, the session will not be remembered. Default is `true`.
    #[serde(rename = "rememberMe", skip_serializing_if = "Option::is_none")]
    pub remember_me: Option<String>,
}

impl SignInEmailPostRequest {
    pub fn new(email: String, password: String) -> SignInEmailPostRequest {
        SignInEmailPostRequest {
            email,
            password,
            callback_url: None,
            remember_me: None,
        }
    }
}

