/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignUpEmailPostRequest {
    /// The name of the user
    #[serde(rename = "name")]
    pub name: String,
    /// The email of the user
    #[serde(rename = "email")]
    pub email: String,
    /// The password of the user
    #[serde(rename = "password")]
    pub password: String,
    /// The URL to use for email verification callback
    #[serde(rename = "callbackURL", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<String>,
}

impl SignUpEmailPostRequest {
    pub fn new(name: String, email: String, password: String) -> SignUpEmailPostRequest {
        SignUpEmailPostRequest {
            name,
            email,
            password,
            callback_url: None,
        }
    }
}

