/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnlinkAccountPostRequest {
    #[serde(rename = "providerId")]
    pub provider_id: String,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
}

impl UnlinkAccountPostRequest {
    pub fn new(provider_id: String) -> UnlinkAccountPostRequest {
        UnlinkAccountPostRequest {
            provider_id,
            account_id: None,
        }
    }
}

