/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserPostRequest {
    /// The name of the user
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The image of the user
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

impl UpdateUserPostRequest {
    pub fn new() -> UpdateUserPostRequest {
        UpdateUserPostRequest {
            name: None,
            image: None,
        }
    }
}

