/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyEmailGet200ResponseUser {
    /// User ID
    #[serde(rename = "id")]
    pub id: String,
    /// User email
    #[serde(rename = "email")]
    pub email: String,
    /// User name
    #[serde(rename = "name")]
    pub name: String,
    /// User image URL
    #[serde(rename = "image")]
    pub image: String,
    /// Indicates if the user email is verified
    #[serde(rename = "emailVerified")]
    pub email_verified: bool,
    /// User creation date
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// User update date
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl VerifyEmailGet200ResponseUser {
    pub fn new(id: String, email: String, name: String, image: String, email_verified: bool, created_at: String, updated_at: String) -> VerifyEmailGet200ResponseUser {
        VerifyEmailGet200ResponseUser {
            id,
            email,
            name,
            image,
            email_verified,
            created_at,
            updated_at,
        }
    }
}

