/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyEmailGet200Response {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::VerifyEmailGet200ResponseUser>>,
    /// Indicates if the email was verified successfully
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<bool>,
}

impl VerifyEmailGet200Response {
    pub fn new() -> VerifyEmailGet200Response {
        VerifyEmailGet200Response {
            user: None,
            status: None,
        }
    }
}

