/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialSignInRequest {
    /// Callback URL to redirect to after the user has signed in
    #[serde(rename = "callbackURL", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<String>,
    #[serde(rename = "newUserCallbackURL", skip_serializing_if = "Option::is_none")]
    pub new_user_callback_url: Option<String>,
    /// Callback URL to redirect to if an error happens
    #[serde(rename = "errorCallbackURL", skip_serializing_if = "Option::is_none")]
    pub error_callback_url: Option<String>,
    /// OAuth2 provider to use
    #[serde(rename = "provider")]
    pub provider: String,
    /// Disable automatic redirection to the provider. Useful for handling the redirection yourself
    #[serde(rename = "disableRedirect", skip_serializing_if = "Option::is_none")]
    pub disable_redirect: Option<String>,
    /// ID token from the provider to sign in the user with id token
    #[serde(rename = "idToken", skip_serializing_if = "Option::is_none")]
    pub id_token: Option<String>,
    /// Array of scopes to request from the provider. This will override the default scopes passed.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<String>,
    /// Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider
    #[serde(rename = "requestSignUp", skip_serializing_if = "Option::is_none")]
    pub request_sign_up: Option<String>,
    /// The login hint to use for the authorization code request
    #[serde(rename = "loginHint", skip_serializing_if = "Option::is_none")]
    pub login_hint: Option<String>,
}

impl SocialSignInRequest {
    pub fn new(provider: String) -> SocialSignInRequest {
        SocialSignInRequest {
            callback_url: None,
            new_user_callback_url: None,
            error_callback_url: None,
            provider,
            disable_redirect: None,
            id_token: None,
            scopes: None,
            request_sign_up: None,
            login_hint: None,
        }
    }
}

