/*
 * Better Auth
 *
 * API Reference for your Better Auth Instance
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialSignIn400Response {
    #[serde(rename = "message")]
    pub message: String,
}

impl SocialSignIn400Response {
    pub fn new(message: String) -> SocialSignIn400Response {
        SocialSignIn400Response {
            message,
        }
    }
}

