name: Build and Push
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
      argo_deployments_path:
        required: true
        type: string
      version_key:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY:
        required: true
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_TOKEN:
        required: true
      DEPLOYMENTS_REPO_TOKEN:
        required: true
jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_NAME: ${{ inputs.deployment_name }}
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: "docker/setup-buildx-action@v3"
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Generate env file
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" > .env
          for var in $(env | grep -v -E "^(GITHUB_|PATH|HOME|USER|SHELL|HOSTNAME|PWD|TERM|SHLVL|_)" | cut -d= -f1); do
            echo "$var=${!var}" >> .env
          done
      - name: "Build and push"
        uses: "docker/build-push-action@v4"
        with:
          context: "."
          file: ${{ inputs.dockerfile_path }}
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.DEPLOYMENT_NAME }}:${{ inputs.environment }}-${{ github.sha }}
          cache-from: type=gha,scope=${{ github.workflow_ref }}
          cache-to: type=gha,scope=${{ github.workflow_ref }},mode=max
          build-args: |
            ENVIRONMENT=${{ inputs.environment }}
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
            ${{ vars }}

  argocd-sync:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          repository: "iAverages/k3s"
          ref: "main"
          token: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
      - name: "Update image version"
        shell: "bash"
        env:
          PUSH_TOKEN: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
          ARGO_DEPLOYMENTS_PATH: ${{ inputs.argo_deployments_path }}
          VERSION_KEY: ${{ inputs.version_key }}
        run: |
          sed -i "s|$VERSION_KEY: .*|$VERSION_KEY: ${{ inputs.environment }}-${{ github.sha }}|g" "$ARGO_DEPLOYMENTS_PATH"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update ${{ env.DEPLOYMENT_NAME }} to ${{ github.sha }}"
          git push https://😛:$PUSH_TOKEN@github.com/iAverages/k3s.git
