name: Build Web

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    uses: ./.github/workflows/base-publish.yaml
    with:
      environment: production
      dockerfile_path: "./apps/website/Dockerfile"
      deployment_name: "machina/web"
      argo_deployments_path: "helm/machina/values/production.yaml"
      version_key: "webVersion"
    secrets: inherit
