name: Build API

on:
  push:
    branches: ["dev"]

concurrency:
  group: dev-api-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/base-publish.yaml
    with:
      environment: dev
      dockerfile_path: "./Dockerfile.api"
      deployment_name: "machina/api"
      argo_deployments_path: "helm/machina/values/dev.yaml"
      version_key: "apiVersion"
    secrets: inherit
