name: Build API

on:
  push:
    branches: ["main"]

concurrency:
  group: production-api-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/base-publish.yaml
    with:
      environment: production
      dockerfile_path: "./apps/api/Dockerfile"
      deployment_name: "machina/api"
      argo_deployments_path: "helm/machina/values/production.yaml"
      version_key: "apiVersion"
    secrets: inherit
